services:
  postgres:
    container_name: mtrade-postgres
    image: postgres:13.3
    environment:
      POSTGRES_USER: mtrade
      POSTGRES_PASSWORD: mtrade-pwd
      POSTGRES_DB: mtrade-db
    ports:
      - "5433:5432"
    volumes:
      - mtrade-postgres-data:/var/lib/postgresql/data
  nextjs-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: mtrade-app
    ports:
      - "3000:3000"
    depends_on:
      - postgres
    env_file:
      - .env.local
    command: npm run dev 
    volumes:
      - /home/ken/Programming/next-mtrade:/usr/src/app

volumes:
  mtrade-postgres-data:

