version: '3.8'

services:
  postgres:
    container_name: mtrade-postgres
    image: postgres:13.3
    environment:
      POSTGRES_USER: mtrade
      POSTGRES_PASSWORD: mtrade
      POSTGRES_DB: mtrade-db
    ports:
      - "5432:5432"
    volumes:
      - mtrade-postgres-data:/var/lib/postgresql/data
    command: >
      bash -c '
      sleep 10 && 
      psql -U mtrade -d mtrade-db -c "INSERT INTO Exchange (id, name) VALUES (gen_random_uuid(), '"'"'Commex'"'"');" &&
      psql -U mtrade -d mtrade-db -c "INSERT INTO Exchange (id, name) VALUES (gen_random_uuid(), '"'"'Kraken'"'"');"'

  nextjs-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: mtrade-app
    ports:
      - "3000:3000"
    depends_on:
      - postgres
    env_file:
      - .env.local

volumes:
  mtrade-postgres-data:
