// eslint-disable-next-line import/no-unresolved
import { KrakenClosedTrade } from "@/types/apiTypes";

const mockClosedTrades: KrakenClosedTrade[] = [
    {
        refid: "1",
        userref: "user1",
        status: "closed",
        opentm: 1637407321,
        starttm: 1637407321,
        expiretm: 1637407421,
        descr: {
            pair: "BTCUSD",
            type: "buy",
            ordertype: "limit",
            price: "50000",
            price2: "0",
            leverage: "3",
            order: "buy",
            close: "limit",
        },
        vol: "1",
        vol_exec: "1",
        cost: "50000",
        fee: "10",
        price: "50000",
        stopprice: "0",
        limitprice: "0",
        misc: "miscellaneous",
        oflags: "oflags",
        reason: null,
        closetm: 1637407421,
    },
    {
        refid: "1",
        userref: "user1",
        status: "closed",
        opentm: 1637407321,
        starttm: 1637407321,
        expiretm: 1637407421,
        descr: {
            pair: "BTCUSD",
            type: "buy",
            ordertype: "limit",
            price: "50000",
            price2: "0",
            leverage: "3",
            order: "buy",
            close: "limit",
        },
        vol: "1",
        vol_exec: "1",
        cost: "50000",
        fee: "10",
        price: "50000",
        stopprice: "0",
        limitprice: "0",
        misc: "miscellaneous",
        oflags: "oflags",
        reason: null,
        closetm: 1637407421,
    },
    {
        refid: "1",
        userref: "user1",
        status: "closed",
        opentm: 1637407321,
        starttm: 1637407321,
        expiretm: 1637407421,
        descr: {
            pair: "BTCUSD",
            type: "buy",
            ordertype: "limit",
            price: "50000",
            price2: "0",
            leverage: "3",
            order: "buy",
            close: "limit",
        },
        vol: "1",
        vol_exec: "1",
        cost: "50000",
        fee: "10",
        price: "50000",
        stopprice: "0",
        limitprice: "0",
        misc: "miscellaneous",
        oflags: "oflags",
        reason: null,
        closetm: 1637407421,
    },
    {
        refid: "1",
        userref: "user1",
        status: "closed",
        opentm: 1637407321,
        starttm: 1637407321,
        expiretm: 1637407421,
        descr: {
            pair: "BTCUSD",
            type: "buy",
            ordertype: "limit",
            price: "50000",
            price2: "0",
            leverage: "3",
            order: "buy",
            close: "limit",
        },
        vol: "1",
        vol_exec: "1",
        cost: "50000",
        fee: "10",
        price: "50000",
        stopprice: "0",
        limitprice: "0",
        misc: "miscellaneous",
        oflags: "oflags",
        reason: null,
        closetm: 1637407421,
    },
    {
        refid: "1",
        userref: "user1",
        status: "closed",
        opentm: 1637407321,
        starttm: 1637407321,
        expiretm: 1637407421,
        descr: {
            pair: "BTCUSD",
            type: "buy",
            ordertype: "limit",
            price: "50000",
            price2: "0",
            leverage: "3",
            order: "buy",
            close: "limit",
        },
        vol: "1",
        vol_exec: "1",
        cost: "50000",
        fee: "10",
        price: "50000",
        stopprice: "0",
        limitprice: "0",
        misc: "miscellaneous",
        oflags: "oflags",
        reason: null,
        closetm: 1637407421,
    },
];

export default mockClosedTrades;
