// Define the Trade type
export interface Trade  {
    exchange: string;
    id: string;
    clientOrderId?: undefined;
    info: {
        id: string;
        refid: null | string;
        userref: null | number;
        status: "closed" | string;
        opentm: string;
        starttm: string;
        expiretm: string;
        descr: Record<string, unknown>;
        vol: string;
        vol_exec: string;
        cost: string;
        fee: string;
        price: string;
        stopprice: string;
        limitprice: string;
        misc: string;
        oflags: string;
        reason: null;
        closetm: string;
    };
    timestamp: number;
    datetime: string;
    lastTradeTimestamp?: undefined;
    status: "closed";
    symbol: string;
    type: "market" | string;
    timeInForce: "IOC";
    postOnly: boolean;
    side: "buy" | string;
    price: number;
    stopPrice?: undefined;
    triggerPrice?: undefined;
    takeProfitPrice?: undefined;
    stopLossPrice?: undefined;
    cost: number;
    amount: number;
    filled: number;
    average: number;
    remaining: number;
    fee: {
        cost: string;
        rate?: undefined;
        currency: "CAD";
    };
    trades: unknown[];
    fees: unknown[];
    lastUpdateTimestamp?: undefined;
    reduceOnly?: undefined;
};